# This compose is for API only, can be used if only wanting the api and not the webui
version: "3.0"
services:
    api:
        build:
          context: ./api
          dockerfile: Dockerfile
          args:
            frontend_host: ":8080"
            backend_host: "localhost:8181"
            jwt_key: "this-pony-dropped-from-sailing-boat"
        env_file:
            - database.env
        depends_on:
            - database
        ports:
            - 8180:8080
        networks: 
            - workflow_net
    database:
        image: "postgres"
        ports:
            - 5432:5432
        env_file:
            - database.env
        volumes:
            - ./api/db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
        networks: 
            - workflow_net
            

networks:
    workflow_net:
        driver: bridge
