- id: 1
  name: listdirectory
  running: false
  topics:
    - found_files
  subscriptions: []
  executioninterval: 10s
  queuesize: 1000
  handler:
    configs:
        properties:
            - name: path
              value: /app/ingress
              description: the path to search for
              required: true
              valid: false
            - name: buffertime
              value: 3600
              description: the time in seconds for how long a found file should be rememberd and not relisted
              required: false
              valid: false
    handler_name: ListDirectory
- id: 2
  name: readfile
  running: false
  topics:
    - file_data
  subscriptions:
    - found_files
  executioninterval: 10s
  queuesize: 1000
  handler:
    configs:
        properties:
            - name: remove_after
              value: true
              description: This property is used to configure if files that are read should be removed after
              required: true
              valid: false
    handler_name: ReadFile
- id: 7
  name: stdout
  running: false
  subscriptions:
    - found_files
  executioninterval: 10s
  queuesize: 1000
  handler:
    configs:
        properties:
            - name: forward
              value: false
              required: true
              valid: true
    handler_name: Stdout

